./configure --cc='gcc -fgnu89-inline -Wall' \
--disable-doc \
--extra-ldflags='-Wl,--start-group' \
--extra-ldflags='-L/home/ndsg/Downloads/mtcp/mtcp/lib' \
--extra-cflags='-I/home/ndsg/Downloads/mtcp/mtcp/include' \
--extra-cflags='-I/home/ndsg/Downloads/mtcp/util/include' \
--extra-ldflags='-L${RTE_SDK}/${RTE_TARGET}lib' \
--extra-ldflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib' \
--extra-libs='-Wl,-ldl' \
--extra-libs='-Wl,-lnuma' \
--extra-libs='-Wl,-lm' \
--extra-libs='-Wl,-lrt' \
--extra-libs='-Wl,--no-whole-archive' \
--extra-libs='-Wl,-lrte_pmd_ifpga_rawdev' \
--extra-libs='-Wl,-lrte_bus_ifpga' \
--extra-libs='-Wl,-lrte_pmd_dpaa2_qdma' \
--extra-libs='-Wl,-lrte_pmd_dpaa2_cmdif' \
--extra-libs='-Wl,-lrte_pmd_skeleton_rawdev' \
--extra-libs='-Wl,-lrte_pmd_opdl_event' \
--extra-libs='-Wl,-lrte_pmd_octeontx' \
--extra-libs='-Wl,-lrte_mempool_octeontx' \
--extra-libs='-Wl,-lrte_pmd_dpaa2_event' \
--extra-libs='-Wl,-lrte_pmd_dpaa_event' \
--extra-libs='-Wl,-lrte_pmd_octeontx_ssovf' \
--extra-libs='-Wl,-lrte_pmd_sw_event' \
--extra-libs='-Wl,-lrte_pmd_skeleton_event' \
--extra-libs='-Wl,-lrte_pmd_virtio_crypto' \
--extra-libs='-Wl,-lrte_pmd_dpaa_sec' \
--extra-libs='-Wl,-lrte_pmd_dpaa2_sec' \
--extra-libs='-Wl,-lrte_pmd_crypto_scheduler' \
--extra-libs='-Wl,-lrte_pmd_null_crypto' \
--extra-libs='-Wl,-lrte_pmd_bbdev_null' \
--extra-libs='-Wl,-lrte_pmd_vmxnet3_uio' \
--extra-libs='-Wl,-lrte_ifcvf_vdpa' \
--extra-libs='-Wl,-lrte_pmd_vhost' \
--extra-libs='-Wl,-lrte_pmd_virtio' \
--extra-libs='-Wl,-lrte_pmd_vdev_netvsc' \
--extra-libs='-Wl,-lrte_pmd_thunderx_nicvf' \
--extra-libs='-Wl,-lrte_pmd_tap' \
--extra-libs='-Wl,-lrte_pmd_sfc_efx' \
--extra-libs='-Wl,-lrte_pmd_softnic' \
--extra-libs='-Wl,-lrte_pmd_ring' \
--extra-libs='-Wl,-lrte_pmd_qede' \
--extra-libs='-Wl,-lrte_pmd_null' \
--extra-libs='-Wl,-lrte_pmd_nfp' \
--extra-libs='-Wl,-lrte_pmd_kni' \
--extra-libs='-Wl,-lrte_pmd_ixgbe' \
--extra-libs='-Wl,-lrte_pmd_i40e' \
--extra-libs='-Wl,-lrte_pmd_failsafe' \
--extra-libs='-Wl,-lrte_pmd_fm10k' \
--extra-libs='-Wl,-lrte_pmd_enic' \
--extra-libs='-Wl,-lrte_pmd_ena' \
--extra-libs='-Wl,-lrte_pmd_e1000' \
--extra-libs='-Wl,-lrte_pmd_dpaa2' \
--extra-libs='-Wl,-lrte_pmd_dpaa' \
--extra-libs='-Wl,-lrte_pmd_cxgbe' \
--extra-libs='-Wl,-lrte_pmd_bond' \
--extra-libs='-Wl,-lrte_pmd_bnxt' \
--extra-libs='-Wl,-lrte_pmd_axgbe' \
--extra-libs='-Wl,-lrte_pmd_avp' \
--extra-libs='-Wl,-lrte_pmd_avf' \
--extra-libs='-Wl,-lrte_pmd_ark' \
--extra-libs='-Wl,-lrte_pmd_af_packet' \
--extra-libs='-Wl,-lrte_mempool_dpaa2' \
--extra-libs='-Wl,-lrte_mempool_dpaa' \
--extra-libs='-Wl,-lrte_mempool_stack' \
--extra-libs='-Wl,-lrte_mempool_bucket' \
--extra-libs='-Wl,-lrte_bus_fslmc' \
--extra-libs='-Wl,-lrte_bus_dpaa' \
--extra-libs='-Wl,-lrte_bus_vdev' \
--extra-libs='-Wl,-lrte_bus_pci' \
--extra-libs='-Wl,-lrte_common_octeontx' \
--extra-libs='-Wl,-lrte_kni' \
--extra-libs='-Wl,-lrte_sched' \
--extra-libs='-Wl,-lrte_reorder' \
--extra-libs='-Wl,-lrte_cmdline' \
--extra-libs='-Wl,-lrte_eal' \
--extra-libs='-Wl,-lrte_pci' \
--extra-libs='-Wl,-lrte_ring' \
--extra-libs='-Wl,-lrte_mempool_ring' \
--extra-libs='-Wl,-lrte_mempool' \
--extra-libs='-Wl,-lrte_timer' \
--extra-libs='-Wl,-lrte_rawdev' \
--extra-libs='-Wl,-lrte_eventdev' \
--extra-libs='-Wl,-lrte_compressdev' \
--extra-libs='-Wl,-lrte_security' \
--extra-libs='-Wl,-lrte_cryptodev' \
--extra-libs='-Wl,-lrte_bbdev' \
--extra-libs='-Wl,-lrte_ethdev' \
--extra-libs='-Wl,-lrte_net' \
--extra-libs='-Wl,-lrte_mbuf' \
--extra-libs='-Wl,-lrte_kvargs' \
--extra-libs='-Wl,-lrte_vhost' \
--extra-libs='-Wl,-lrte_member' \
--extra-libs='-Wl,-lrte_hash' \
--extra-libs='-Wl,-lrte_cfgfile' \
--extra-libs='-Wl,--whole-archive' \
--extra-libs='-Wl,-lrte_bpf' \
--extra-libs='-Wl,-lrte_efd' \
--extra-libs='-Wl,-lrte_power' \
--extra-libs='-Wl,-lrte_latencystats' \
--extra-libs='-Wl,-lrte_bitratestats' \
--extra-libs='-Wl,-lrte_metrics' \
--extra-libs='-Wl,-lrte_jobstats' \
--extra-libs='-Wl,--no-whole-archive' \
--extra-libs='-Wl,-lrte_acl' \
--extra-libs='-Wl,--whole-archive' \
--extra-libs='-Wl,-lrte_lpm' \
--extra-libs='-Wl,-lrte_meter' \
--extra-libs='-Wl,-lrte_gso' \
--extra-libs='-Wl,-lrte_gro' \
--extra-libs='-Wl,-lrte_ip_frag' \
--extra-libs='-Wl,-lrte_distributor' \
--extra-libs='-Wl,-lrte_pdump' \
--extra-libs='-Wl,-lrte_port' \
--extra-libs='-Wl,-lrte_table' \
--extra-libs='-Wl,-lrte_pipeline' \
--extra-libs='-Wl,-lrte_flow_classify' \
--extra-libs='-lgmp' \
--extra-libs='-ldl' \
--extra-libs='-lrt' \
--extra-libs='-lpthread' \
--extra-libs='-lmtcp' \
--extra-libs='-lnuma' \
--extra-libs='-march=native' \
--extra-libs='-lrt' && \

cp /home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/NewLists/new_protocol_list.c \
/home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/libavformat/protocol_list.c && \

cp /home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/NewLists/new_muxer_list.c \
/home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/libavformat/muxer_list.c && \

cp /home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/NewLists/new_demuxer_list.c \
/home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/libavformat/demuxer_list.c && \

make