./configure --cc='gcc -fgnu89-inline' \
--disable-doc \
--extra-cflags='-march=native' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/mtcp/lib' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/mtcp/lib -lnuma' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/mtcp/lib -lmtcp' \
--extra-cflags='-I/home/ndsg/Downloads/mtcp/mtcp/include' \
--extra-cflags='-I/home/ndsg/Downloads/mtcp/util/include' \
--extra-cflags='-L${RTE_SDK}/${RTE_TARGET}lib' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_flow_classify' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pipeline' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_table' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_port' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pdump' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_distributor' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_ip_frag' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_gro' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_gso' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_meter' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_lpm' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_acl' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_jobstats' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_metrics' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bitratestats' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_latencystats' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_power' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_efd' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bpf' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_cfgfile' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_hash' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_member' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_vhost' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_kvargs' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mbuf' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_net' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_ethdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bbdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_cryptodev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_security' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_compressdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_eventdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_rawdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_timer' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool_ring' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_ring' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pci' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_eal' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_cmdline' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_reorder' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_sched' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_kni' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_common_octeontx' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bus_pci' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bus_vdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bus_dpaa' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bus_fslmc' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool_bucket' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool_stack' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool_dpaa' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool_dpaa2' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_af_packet' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_ark' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_avf' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_avp' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_axgbe' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_bnxt' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_bond' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_cxgbe' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa2' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_e1000' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_ena' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_enic' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_fm10k' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_failsafe' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_i40e' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_ixgbe' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_kni' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_nfp' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_null' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_qede' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_ring' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_softnic' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_sfc_efx' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_tap' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_thunderx_nicvf' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_vdev_netvsc' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_virtio' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_vhost' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_ifcvf_vdpa' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_vmxnet3_uio' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_bbdev_null' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_null_crypto' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_crypto_scheduler' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa2_sec' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa_sec' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_virtio_crypto' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_skeleton_event' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_sw_event' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_octeontx_ssovf' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa_event' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa2_event' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_mempool_octeontx' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_octeontx' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_opdl_event' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_skeleton_rawdev' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa2_cmdif' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_dpaa2_qdma' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_bus_ifpga' \
--extra-cflags='-L/home/ndsg/Downloads/mtcp/dpdk/x86_64-native-linuxapp-gcc/lib -lrte_pmd_ifpga_rawdev' && \

cp /home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/NewLists/new_protocol_list.c \
/home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/libavformat/protocol_list.c && \

cp /home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/NewLists/new_muxer_list.c \
/home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/libavformat/muxer_list.c && \

cp /home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/NewLists/new_demuxer_list.c \
/home/ndsg/Downloads/mtcp/apps/FFmpeg-release-4.3/libavformat/demuxer_list.c && \

make